//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCelerium.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Commerciaux
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Display(Name="Numero Commercial")]
        public string AgentId { get; set; }
        [ScaffoldColumn(false)]

        public string AgentPass { get; set; }
         [Display(Name = "Nom Commercial")]
         [Required(ErrorMessage = "Le {0} est obligatoire")]
        public string AgentName { get; set; }
         [Display(Name="Actif")]
        public bool AgentActif { get; set; }
         [Display(Name = "Telephone")]
        [DataType(DataType.PhoneNumber)]
         [Required(ErrorMessage = "Le {0} est obligatoire")]
        public Nullable<int> AgentTel { get; set; }
    }
}
