//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace iCelerium.Models
{
    using System;

    public partial class TTransaction
    {
        [Key]
        public int id { get; set; }
        [Display(Name = "Numero Commercial")]
        public string AgentId { get; set; }
        public string ClientId { get; set; }
        public double Credit { get; set; }
        public double Debit { get; set; }
        public double SoldeOuverture { get; set; }
        public double SoldeFermeture { get; set; }
        public double Description { get; set; }
        public System.DateTime DateOperation { get; set; }
    }
}
